name: symphony_music_app
description: "A Music App Mobile Flutter project - Symphony."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  provider: ^6.0.5

  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/music/
    - assets/singer_avatars/
    - assets/user_avatars/
    - assets/album_images/
    - assets/song_images/
    - assets/lrc/
    - assets/lyrics/
